const results2 = [
    [],
    [],
    [
        {
            "providerId": "4",
            "nameprovider": "Doctored",
            "planId": "402",
            "nameplan": "3000",
            "documentpath": "DIPTICO COMERCIAL DOCTORED 3000.pdf",
            "copay": "NO",
            "medicalguide": "*****",
            "internation": "HabitaciÃ³n Individual",
            "doctorathome": "Sin Copago",
            "odontology": "*****",
            "orthodontics": "Sin limite de edad",
            "refund": "Si",
            "clinics": " CAPITAL FEDERAL\r\nCEMIC\r\nCLINICA SAN CAMILO\r\nCLINICA LA SAGRADA FAMILIA\r\nCLINICA BAZTERRICA\r\nHOSPITAL BRITANICO DE BS AS\r\nICBA\r\nFLENI\r\nCLINICA ADVENTISTA DE BELGRANO\r\nSANATORIO OTAMENDI\r\nCLINICA SANTA ISABEL\r\nFUNDACION HOSPITALARIA DE NIÃ‘OS\r\nSANATORIO MATER DEI\r\nHOSPITAL ALEMAN\r\nINSTITUTO ALEXANDER FLEMING\r\nSANATORIO ANCHORENA\r\n\r\nZONA NORTE\r\nSANATORIO LAS LOMAS\r\nSANATORIO SAN LUCAS\r\nHOSPITAL PRIVADO DR. ALBERTO DUHAU\r\nCONSULTORIO MEDICO HEPTA\r\nCLINICA PRIVADA DEL FATIMA\r\nSANATORIO ANCHORENA\r\nCENTRO MEDICO DERAGOPYAN\r\nHOSPITAL PRIVADO MODELO\r\nCENTRO MEDICO PREVENTUS\r\nCLINICA PRIVADA CRISTO REY\r\nCLINICA SAGRADO CORAZON DE DONTORCUATO\r\nHOSPITAL BRITANICO (VICENTE LOPEZ)\r\nCENTRO MEDICO MARTIN Y OMAR\r\nSANATORIO ANCHORENA (SAN MARTIN)\r\nMEDICINA ASISTENCIA DE SERVICIOS M.A.S.\r\n\r\nZONA OESTE\r\nCASA HOSPITAL SAN JUAN DE DIOS\r\nCLINICA MODELO DE MORON\r\nSANATORIO NUESTRA SEÃ‘ORA DEL PILAR\r\nDIM\r\nCLINICA DEL BUEN PASTOR\r\nSANATORIO PRIVADO FIGUEROA PAREDES\r\nSANATORIOS DEL OESTE ITUZAINGO\r\nSANATORIOS DEL OESTE MERLO\r\nCEPEM\r\nSANATORIO PRIVADO SAN MAURICIO\r\nCLINICA CRUZ CELESTE\r\nSANATORIO PRIVADO FIGUEROA PAREDES\r\n\r\nZONA SUR\r\nNUEVO SANATORIO BERAZATEGUI\r\nSANATORIO ITOIZ\r\nCLINICA BOEDO\r\nSANATORIO BERNAL\r\nCLINICA DEL NIÃ‘O QUILMES\r\nCLINICA PRIVADA DE RANELAGH\r\nCLINICA NUESTRA SEÃ‘ORA DE LA DULCE ESPERA\r\nSANATORIO SAN JUAN\r\nSANATORIO JUNCAL\r\nSANATORIO MODELO DE ADROGUE\r\nHOSPITAL BRITANICO (LOMAS y LANUS)\r\nCLINICA PRIVADA DE MONTEGRANDE ",
            "price": 82040.86
        }
    ],
    [
        {
            "providerId": "3",
            "nameprovider": "Premedic",
            "planId": "302",
            "nameplan": "300",
            "documentpath": "Prueba plan medico.pdf",
            "copay": "Si",
            "medicalguide": "Si",
            "internation": "Si",
            "doctorathome": "Si",
            "odontology": "Si",
            "orthodontics": "Si",
            "refund": "Si",
            "clinics": "Clinica A, Clinica B, Clinica C",
            "price": 57610.03
        },
        {
            "providerId": "3",
            "nameprovider": "Premedic",
            "planId": "303",
            "nameplan": "400",
            "documentpath": "Prueba plan medico.pdf",
            "copay": "Si",
            "medicalguide": "Si",
            "internation": "Si",
            "doctorathome": "Si",
            "odontology": "Si",
            "orthodontics": "Si",
            "refund": "Si",
            "clinics": "Clinica A, Clinica B, Clinica C",
            "price": 61754.03
        }
    ],
    [
        {
            "providerId": "2",
            "nameprovider": "Galeno",
            "planId": "204",
            "nameplan": "550",
            "documentpath": null,
            "copay": "NO",
            "medicalguide": "*****",
            "internation": "HabitaciÃ³n Individual",
            "doctorathome": "Sin Copago",
            "odontology": "****",
            "orthodontics": "De 5 a 25 aÃ±os",
            "refund": "SI",
            "clinics": "CAPITAL FEDERAL\r\nSANATORIO LA TRINIDAD MITRE\r\nSANATORIO LA TRINIDAD PALERMO\r\nSANATORIO DUPUYTREN\r\nCEMIC\r\nCLIÌ�NICA BAZTERRICA\r\nCLIÌ�NICA DEL SOL\r\nCLIÌ�NICA MATERNIDAD SANTA ISABEL\r\nCLIÌ�NICA LA SAGRADA FAMILIA\r\nCLIÌ�NICA OFTALMOLOÌ�GICA MALBRAN\r\nCLIÌ�NICA Y MATERNIDAD SUIZO ARG.\r\nCLIÌ�NICA ZABALA\r\nCLIÌ�NICA SAN CAMILO\r\nFLENI\r\nFUNDACIOÌ�N FAVALORO\r\nHOSPITAL ALEMAN\r\nHOSPITAL BRITANICO\r\nI.A.D.T.\r\nSANATORIO FINOCHIETTO\r\nSANATORIO MATER DEI\r\nSANATORIO LOS ARCOS\r\nSANATORIO OTAMENDI\r\n\r\nZONA NORTE\r\nSANATORIO LA TRINIDAD SAN ISIDRO\r\nSANATORIO LA TRINIDAD JOCKEY CLUB\r\nCLIÌ�NICA OLIVOS\r\nHOSPITAL PRIVADO MODELO\r\nHOSPITAL UNIVERSITARIO AUSTRAL\r\nSANATORIO SAN LUCAS\r\nSANATORIO LAS LOMAS\r\nCENTRO MEÌ�DICO DEL TALAR\r\nCLIÌ�NICA PRIVADA FAÌ�TIMA\r\n\r\nZONA OESTE\r\nSANATORIO LA TRINIDAD RAMOS MEJIA\r\nHOSPITAL SAN JUAN DE DIOS\r\nCLIÌ�NICA MODELO DE MORON\r\nCLIÌ�NICA BESONE\r\nCLIÌ�NICA PRIVADA DEL BUEN PASTOR\r\nHOSPITAL DR. ALBERTO DUHAU\r\nCLIÌ�NICA CORPORACIOÌ�N MEÌ�DICA DE SAN MARTIN\r\nSANATORIO PRICADO FIGUEROA PAREDES\r\nCLIÌ�NICA MODELO DE CASEROS\r\n\r\nZONA SUR\r\nSANATORIO LA TRINIDAD QUILMES\r\nCLIÌ�NICA BOEDO\r\nCLIÌ�NICA ESTRADA\r\nCLIÌ�NICA PRIVADA DE RANELAGH\r\nINSTITUTO MEÌ�DICO ADROGUE (IMA)\r\nSANATORIO SAN FRANCISCO\r\nSANATORIO JUNCAL\r\nCLIÌ�NICA DEL NINÌƒO DE QUILMES\r\nCLIÌ�NICA PRIVADA SAN VICENTE ",
            "price": "151247.77"
        },
        {
            "providerId": "2",
            "nameprovider": "Galeno",
            "planId": "203",
            "nameplan": "440",
            "documentpath": null,
            "copay": "NO",
            "medicalguide": "*****",
            "internation": "HabitaciÃ³n Individual",
            "doctorathome": "Sin Copago",
            "odontology": "****",
            "orthodontics": "De 5 a 25 aÃ±os",
            "refund": "SI",
            "clinics": "CAPITAL FEDERAL\r\nSANATORIO LA TRINIDAD MITRE\r\nSANATORIO LA TRINIDAD PALERMO\r\nSANATORIO DUPUYTREN\r\nCEMIC\r\nCLIÌ�NICA BAZTERRICA\r\nCLIÌ�NICA DEL SOL\r\nCLIÌ�NICA MATERNIDAD SANTA ISABEL\r\nCLIÌ�NICA LA SAGRADA FAMILIA\r\nCLIÌ�NICA OFTALMOLOÌ�GICA MALBRAN\r\nCLIÌ�NICA Y MATERNIDAD SUIZO ARG.\r\nCLIÌ�NICA ZABALA\r\nCLIÌ�NICA SAN CAMILO\r\nFLENI\r\nFUNDACIOÌ�N FAVALORO\r\nHOSPITAL ALEMAN\r\nHOSPITAL BRITANICO\r\nI.A.D.T.\r\nSANATORIO FINOCHIETTO\r\nSANATORIO MATER DEI\r\nSANATORIO LOS ARCOS\r\nSANATORIO OTAMENDI\r\n\r\nZONA NORTE\r\nSANATORIO LA TRINIDAD SAN ISIDRO\r\nSANATORIO LA TRINIDAD JOCKEY CLUB\r\nCLIÌ�NICA OLIVOS\r\nHOSPITAL PRIVADO MODELO\r\nHOSPITAL UNIVERSITARIO AUSTRAL\r\nSANATORIO SAN LUCAS\r\nSANATORIO LAS LOMAS\r\nCENTRO MEÌ�DICO DEL TALAR\r\nCLIÌ�NICA PRIVADA FAÌ�TIMA\r\n\r\nZONA OESTE\r\nSANATORIO LA TRINIDAD RAMOS MEJIA\r\nHOSPITAL SAN JUAN DE DIOS\r\nCLIÌ�NICA MODELO DE MORON\r\nCLIÌ�NICA BESONE\r\nCLIÌ�NICA PRIVADA DEL BUEN PASTOR\r\nHOSPITAL DR. ALBERTO DUHAU\r\nCLIÌ�NICA CORPORACIOÌ�N MEÌ�DICA DE SAN MARTIN\r\nSANATORIO PRICADO FIGUEROA PAREDES\r\nCLIÌ�NICA MODELO DE CASEROS\r\n\r\nZONA SUR\r\nSANATORIO LA TRINIDAD QUILMES\r\nCLIÌ�NICA BOEDO\r\nCLIÌ�NICA ESTRADA\r\nCLIÌ�NICA PRIVADA DE RANELAGH\r\nINSTITUTO MEÌ�DICO ADROGUE (IMA)\r\nSANATORIO SAN FRANCISCO\r\nSANATORIO JUNCAL\r\nCLIÌ�NICA DEL NINÌƒO DE QUILMES\r\nCLIÌ�NICA PRIVADA SAN VICENTE ",
            "price": "96844.64"
        },
        {
            "providerId": "3",
            "nameprovider": "Premedic",
            "planId": "304",
            "nameplan": "500",
            "documentpath": "Prueba plan medico.pdf",
            "copay": "Si",
            "medicalguide": "Si",
            "internation": "Si",
            "doctorathome": "Si",
            "odontology": "Si",
            "orthodontics": "Si",
            "refund": "Si",
            "clinics": "Clinica A, Clinica B, Clinica C",
            "price": 95774
        },
        {
            "providerId": "2",
            "nameprovider": "Galeno",
            "planId": "202",
            "nameplan": "330",
            "documentpath": null,
            "copay": "NO",
            "medicalguide": "****",
            "internation": "HabitaciÃ³n Individual",
            "doctorathome": "Con copago",
            "odontology": "***",
            "orthodontics": "De 5 a 8 aÃ±os",
            "refund": "SI",
            "clinics": "CAPITAL FEDERAL\r\nSANATORIO LA TRINIDAD MITRE\r\nSANATORIO LA TRINIDAD PALERMO\r\nSANATORIO DUPUYTREN\r\nCEMIC\r\nCLIÌ�NICA BAZTERRICA\r\nCLIÌ�NICA DEL SOL\r\nCLIÌ�NICA MATERNIDAD SANTA ISABEL\r\nCLIÌ�NICA LA SAGRADA FAMILIA\r\nCLIÌ�NICA OFTALMOLOÌ�GICA MALBRAN\r\nCLIÌ�NICA Y MATERNIDAD SUIZO ARG.\r\nCLIÌ�NICA ZABALA\r\nCLIÌ�NICA SAN CAMILO\r\nFLENI\r\nFUNDACIOÌ�N FAVALORO\r\nHOSPITAL BRITANICO\r\nI.A.D.T.\r\nSANATORIO FINOCHIETTO\r\nSANATORIO MATER DEI\r\nSANATORIO OTAMENDI\r\n\r\nZONA NORTE\r\nSANATORIO LA TRINIDAD SAN ISIDRO\r\nSANATORIO LA TRINIDAD JOCKEY CLUB\r\nCLIÌ�NICA OLIVOS\r\nHOSPITAL PRIVADO MODELO\r\nHOSPITAL UNIVERSITARIO AUSTRAL\r\nSANATORIO SAN LUCAS\r\nSANATORIO LAS LOMAS\r\nCENTRO MEÌ�DICO DEL TALAR\r\nCLIÌ�NICA PRIVADA FAÌ�TIMA\r\n\r\nZONA OESTE\r\nSANATORIO LA TRINIDAD RAMOS MEJIA\r\nHOSPITAL SAN JUAN DE DIOS\r\nCLIÌ�NICA MODELO DE MORON\r\nCLIÌ�NICA BESONE\r\nCLIÌ�NICA PRIVADA DEL BUEN PASTOR\r\nHOSPITAL DR. ALBERTO DUHAU\r\nCLIÌ�NICA CORPORACIOÌ�N MEÌ�DICA DE SAN MARTIN\r\nSANATORIO PRICADO FIGUEROA PAREDES\r\nCLIÌ�NICA MODELO DE CASEROS\r\n\r\nZONA SUR\r\nSANATORIO LA TRINIDAD QUILMES\r\nCLIÌ�NICA BOEDO\r\nCLIÌ�NICA ESTRADA\r\nCLIÌ�NICA PRIVADA DE RANELAGH\r\nINSTITUTO MEÌ�DICO ADROGUE (IMA)\r\nSANATORIO SAN FRANCISCO\r\nSANATORIO JUNCAL\r\nCLIÌ�NICA DEL NINÌƒO DE QUILMES\r\nCLIÌ�NICA PRIVADA SAN VICENTE ",
            "price": "75087.79"
        },
        {
            "providerId": "2",
            "nameprovider": "Galeno",
            "planId": "200",
            "nameplan": "220",
            "documentpath": null,
            "copay": "NO",
            "medicalguide": "***",
            "internation": "HabitaciÃ³n Individual",
            "doctorathome": "Con copago",
            "odontology": "**",
            "orthodontics": "De 5 a 25 aÃ±os",
            "refund": "NO",
            "clinics": "CAPITAL FEDERAL\r\nSANATORIO LA TRINIDAD MITRE\r\nSANATORIO LA TRINIDAD PALERMO\r\nSANATORIO DUPUYTREN\r\nCEMIC\r\nCLIÌ�NICA BAZTERRICA\r\nCLIÌ�NICA MATERNIDAD SANTA ISABEL\r\nCLIÌ�NICA LA SAGRADA FAMILIA\r\nCLIÌ�NICA ZABALA\r\nCLIÌ�NICA SAN CAMILO\r\nSANATORIO FINOCHIETTO \r\n\r\nZONA NORTE\r\nSANATORIO LA TRINIDAD SAN ISIDRO\r\nSANATORIO LA TRINIDAD JOCKEY CLUB\r\nCLIÌ�NICA OLIVOS\r\nHOSPITAL PRIVADO MODELO\r\nHOSPITAL UNIVERSITARIO AUSTRAL\r\nCENTRO MEÌ�DICO DEL TALAR\r\nCLIÌ�NICA PRIVADA FAÌ�TIMA\r\n\r\nZONA OESTE\r\nSANATORIO LA TRINIDAD RAMOS MEJIA\r\nHOSPITAL SAN JUAN DE DIOS\r\nCLIÌ�NICA MODELO DE MORON\r\nCLIÌ�NICA BESONE\r\nCLIÌ�NICA PRIVADA DEL BUEN PASTOR\r\nHOSPITAL DR. ALBERTO DUHAU\r\nCLIÌ�NICA CORPORACIOÌ�N MEÌ�DICA DE SAN MARTIN\r\nSANATORIO PRICADO FIGUEROA PAREDES\r\nCLIÌ�NICA MODELO DE CASEROS\r\n\r\nZONA SUR\r\nSANATORIO LA TRINIDAD QUILMES\r\nCLIÌ�NICA BOEDO\r\nCLIÌ�NICA ESTRADA\r\nCLIÌ�NICA PRIVADA DE RANELAGH\r\nINSTITUTO MEÌ�DICO ADROGUE (IMA)\r\nCLIÌ�NICA DEL NINÌƒO DE QUILMES\r\nCLIÌ�NICA PRIVADA SAN VICENTE",
            "price": "58566.55"
        },
        {
            "providerId": "4",
            "nameprovider": "Doctored",
            "planId": "401",
            "nameplan": "2000",
            "documentpath": "DIPTICO COMERCIAL DOCTORED 2000.pdf",
            "copay": "NO",
            "medicalguide": "***",
            "internation": "HabitaciÃ³n Compartida",
            "doctorathome": "Sin Copago",
            "odontology": "***",
            "orthodontics": "De 5 a 8 aÃ±os",
            "refund": "NO",
            "clinics": "CAPITAL FEDERAL\r\nCEMIC\r\nCLINICA SAN CAMILO\r\nCLINICA LA SAGRADA FAMILIA\r\nCLINICA BAZTERRICA\r\nHOSPITAL BRITANICO DE BS AS\r\nICBA\r\nCENTRO MEDICO ROSSI\r\nCLINICA SANTA ISABEL\r\nFUNDACION HOSPITALARIA DE NIÃ‘OS\r\nCENTRO MEDICO DOCTOR RED\r\nINSTITUTO MEDICO DE ALTA TECNOLOGÃ�A\r\nINSTITUTO ALEXANDER FLEMING\r\nSANATORIO ANCHORENA   \r\n\r\nZONA NORTE\r\nCENTRO MEDICO DERAGOPYAN\r\nHOSPITAL PRIVADO MODELO\r\nHOSPITAL PRIVADO DR. ALBERTO DUHAU\r\nCONSULTORIO MEDICO HEPTA\r\nCLINICA PRIVADA DEL FATIMA\r\nSANATORIO ANCHORENA\r\nCENTRO MEDICO PREVENTUS\r\nCLINICA PRIVADA CRISTO REY\r\nCLINICA SAGRADO CORAZON DE DONTORCUATO\r\nGRUPO MEDICO SAN ISIDRO\r\nHOSPITAL BRITANICO (VICENTE LOPEZ)\r\nSANATORIO ANCHORENA (SAN MARTIN)\r\nMEDICINA ASISTENCIA DE SERVICIOS M.A.S.\r\n\r\nZONA OESTE\r\nCASA HOSPITAL SAN JUAN DE DIOS\r\nCLINICA MODELO DE MORON\r\nSANATORIO NUESTRA SEÃ‘ORA DEL PILAR\r\nDIM\r\nCLINICA DEL BUEN PASTOR\r\nSANATORIO PRIVADO FIGUEROA PAREDES\r\nSANATORIOS DEL OESTE ITUZAINGO\r\nSANATORIOS DEL OESTE MERLO\r\nCEPEM\r\nSANATORIO PRIVADO SAN MAURICIO\r\nCLINICA CRUZ CELESTE\r\nSANATORIO PRIVADO FIGUEROA PAREDES\r\n\r\nZONA SUR\r\nNUEVO SANATORIO BERAZATEGUI\r\nSANATORIO ITOIZ\r\nCLINICA BOEDO\r\nSANATORIO BERNAL\r\nCLINICA DEL NIÃ‘O QUILMES\r\nCLINICA PRIVADA DE RANELAGH\r\nCLINICA NUESTRA SEÃ‘ORA DE LA DULCE ESPERA\r\nSANATORIO SAN JUAN\r\nSANATORIO JUNCAL\r\nSANATORIO MODELO DE ADROGUE\r\nHOSPITAL BRITANICO (LOMAS y LANUS)\r\nCLINICA PRIVADA DE MONTEGRANDE",
            "price": 56332.77
        },
        {
            "providerId": "3",
            "nameprovider": "Premedic",
            "planId": "301",
            "nameplan": "200",
            "documentpath": "Prueba plan medico.pdf",
            "copay": "Si",
            "medicalguide": "Si",
            "internation": "Si",
            "doctorathome": "Si",
            "odontology": "Si",
            "orthodontics": "Si",
            "refund": "Si",
            "clinics": "Clinica A, Clinica B, Clinica C",
            "price": 48525
        },
        {
            "providerId": "4",
            "nameprovider": "Doctored",
            "planId": "400",
            "nameplan": "1000",
            "documentpath": "DIPTICO COMERCIAL DOCTORED 1000.pdf",
            "copay": "NO",
            "medicalguide": "**",
            "internation": "HabitaciÃ³n Compartida",
            "doctorathome": "Sin Copago",
            "odontology": "***",
            "orthodontics": "De 5 a 8 aÃ±os",
            "refund": "NO",
            "clinics": "CAPITAL FEDERAL\r\nSANATORIO COLEGIALES\r\nHOSPITAL NAVAL BUENOS AIRES\r\nCLINICA LA SAGRADA FAMILIA\r\nCLINICA BAZTERRICA\r\nHOSPITAL UNIVERSITARIO UAI SALUD\r\nCLINICA CIUDAD DE LA VIDA\r\nSANATORIO RAMON CEJEIRO\r\nCLINICA SANTA ISABEL\r\nFUNDACION HOSPITALARIA DE NIÃ‘OS\r\nCENTRO MEDICO DOCTOR RED\r\nGRUPO MEDICO AIRES SALUD\r\nINSTITUTO ALEXANDER FLEMING\r\nBELGRANO MEDICINA INTEGRAL\r\n\r\nZONA NORTE\r\nCLINICA AIRES DE PACHECO\r\nHOSPITAL PRIVADO MODELO\r\nHOSPITAL PRIVADO DR. ALBERTO DUHAU\r\nCLINICA LOS ALMENDROS\r\nCLINICA PRIVADA DEL FATIMA\r\nSANATORIO SAN PABLO\r\nCENTRO MEDICO PREVENTUS\r\nCLINICA PRIVADA CRISTO REY\r\nCLINICA SAGRADO CORAZON DE DONTORCUATO\r\nGRUPO MEDICO SAN ISIDRO\r\nROSAMOND\r\nCENTRO MEDICO VICTORIA\r\nMEDICINA ASISTENCIA DE SERVICIOS M.A.S.\r\n\r\nZONA OESTE\r\nCASA HOSPITAL SAN JUAN DE DIOS\r\nCLINICA MODELO DE MORON\r\nSANATORIO NUESTRA SEÃ‘ORA DEL PILAR\r\nCENTRO MEDICO ENTRE RIOS\r\nCLINICA DEL BUEN PASTOR\r\nSANATORIO PRIVADO FIGUEROA PAREDES\r\nSANATORIOS DEL OESTE ITUZAINGO\r\nSANATORIOS DEL OESTE MERLO\r\nCLINICA ALCORTA\r\nSANATORIO PRIVADO SAN MAURICIO\r\nCLINICA CRUZ CELESTE\r\nSANATORIO PRIVADO FIGUEROA PAREDES\r\n\r\nZONA SUR\r\nNUEVO SANATORIO BERAZATEGUI\r\nPOLICLINICO REGIONAL DE AVELLANEDA\r\nCLINICA BOEDO\r\nSANATORIO BERNAL\r\nCLINICA DEL NIÃ‘O QUILMES\r\nCLINICA PRIVADA DE RANELAGH\r\nCLINICA NUESTRA SEÃ‘ORA DE LA DULCE ESPERA\r\nSANATORIO SAN JUAN\r\nCENTRO MEDICO MEDIPRIM\r\nSANATORIO MODELO DE ADROGUE\r\nPOLICLINICO LOMAS\r\nCLINICA PRIVADA DE MONTEGRANDE",
            "price": 42379.75
        },
        {
            "providerId": "3",
            "nameprovider": "Premedic",
            "planId": "300",
            "nameplan": "C-100",
            "documentpath": "Prueba plan medico.pdf",
            "copay": "Si",
            "medicalguide": "Si",
            "internation": "Si",
            "doctorathome": "Si",
            "odontology": "Si",
            "orthodontics": "Si",
            "refund": "Si",
            "clinics": "Clinica A, Clinica B, Clinica C",
            "price": 38629
        }
    ]
]

export const results = [
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-doctored.png',
        name: 'DOCTORED',
        plan: 'DOCTORED 1000',
        price: '$25.257,42',
        discount: '$35.000,42',
        reintegros: false,
        internacion: 'Hab. compartida',
        medico: 'Con límite y copago',
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '40%',
        odontologia: true,
        ortodoncia: 'De 5 a 25 años',
        implantes: false,
        oftalmologia: true,
        optica: '1 par x año',
        mental: '30 sesiones',
        kinesiologia: '25 sesiones',
        maternidad: true,
        cirugia: false,
        cobertura: 'AMBA'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-ps.png',
        name: 'Prev. Salud',
        plan: 'A5',
        price: '$20.000,22',
        discount: null,
        reintegros: true,
        internacion: 'Hab. individual',
        medico: true,
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '50%',
        odontologia: true,
        ortodoncia: true,
        implantes: true,
        oftalmologia: true,
        optica: 'Reintegro anual',
        mental: '30 sesiones',
        kinesiologia: true,
        maternidad: true,
        cirugia: '1 zona cada 2 años',
        cobertura: 'Nacional'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-sarcor.png',
        name: 'SancorSalud',
        plan: '1000 B CC',
        price: '$34.016',
        discount: null,
        reintegros: false,
        internacion: 'Hab. compartida',
        medico: 'Con límite y copago',
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '40%',
        odontologia: true,
        ortodoncia: 'De 5 a 25 años',
        implantes: false,
        oftalmologia: true,
        optica: '1 par x año',
        mental: '30 sesiones',
        kinesiologia: '25 sesiones',
        maternidad: true,
        cirugia: false,
        cobertura: 'AMBA'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-premedic.png',
        name: 'PREMEDIC',
        plan: '500',
        price: '$52.257,12',
        discount: null,
        reintegros: true,
        internacion: 'Hab. individual',
        medico: true,
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '50%',
        odontologia: true,
        ortodoncia: true,
        implantes: true,
        oftalmologia: true,
        optica: 'Reintegro anual',
        mental: '30 sesiones',
        kinesiologia: true,
        maternidad: true,
        cirugia: '1 zona cada 2 años',
        cobertura: 'Nacional'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-doctored.png',
        name: 'DOCTORED',
        plan: 'DOCTORED 1000',
        price: '$25.257,42',
        discount: '$35.000,42',
        reintegros: false,
        internacion: 'Hab. compartida',
        medico: 'Con límite y copago',
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '40%',
        odontologia: true,
        ortodoncia: 'De 5 a 25 años',
        implantes: false,
        oftalmologia: true,
        optica: '1 par x año',
        mental: '30 sesiones',
        kinesiologia: '25 sesiones',
        maternidad: true,
        cirugia: false,
        cobertura: 'AMBA'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-ps.png',
        name: 'Prev. Salud',
        plan: 'A5',
        price: '$20.000,22',
        discount: null,
        reintegros: true,
        internacion: 'Hab. individual',
        medico: true,
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '50%',
        odontologia: true,
        ortodoncia: true,
        implantes: true,
        oftalmologia: true,
        optica: 'Reintegro anual',
        mental: '30 sesiones',
        kinesiologia: true,
        maternidad: true,
        cirugia: '1 zona cada 2 años',
        cobertura: 'Nacional'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-sarcor.png',
        name: 'SancorSalud',
        plan: '1000 B CC',
        price: '$34.016',
        discount: null,
        reintegros: false,
        internacion: 'Hab. compartida',
        medico: 'Con límite y copago',
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '40%',
        odontologia: true,
        ortodoncia: 'De 5 a 25 años',
        implantes: false,
        oftalmologia: true,
        optica: '1 par x año',
        mental: '30 sesiones',
        kinesiologia: '25 sesiones',
        maternidad: true,
        cirugia: false,
        cobertura: 'AMBA'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-premedic.png',
        name: 'PREMEDIC',
        plan: '500',
        price: '$52.257,12',
        discount: null,
        reintegros: true,
        internacion: 'Hab. individual',
        medico: true,
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '50%',
        odontologia: true,
        ortodoncia: true,
        implantes: true,
        oftalmologia: true,
        optica: 'Reintegro anual',
        mental: '30 sesiones',
        kinesiologia: true,
        maternidad: true,
        cirugia: '1 zona cada 2 años',
        cobertura: 'Nacional'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-doctored.png',
        name: 'DOCTORED',
        plan: 'DOCTORED 1000',
        price: '$25.257,42',
        discount: '$35.000,42',
        reintegros: false,
        internacion: 'Hab. compartida',
        medico: 'Con límite y copago',
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '40%',
        odontologia: true,
        ortodoncia: 'De 5 a 25 años',
        implantes: false,
        oftalmologia: true,
        optica: '1 par x año',
        mental: '30 sesiones',
        kinesiologia: '25 sesiones',
        maternidad: true,
        cirugia: false,
        cobertura: 'AMBA'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-ps.png',
        name: 'Prev. Salud',
        plan: 'A5',
        price: '$20.000,22',
        discount: null,
        reintegros: true,
        internacion: 'Hab. individual',
        medico: true,
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '50%',
        odontologia: true,
        ortodoncia: true,
        implantes: true,
        oftalmologia: true,
        optica: 'Reintegro anual',
        mental: '30 sesiones',
        kinesiologia: true,
        maternidad: true,
        cirugia: '1 zona cada 2 años',
        cobertura: 'Nacional'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-sarcor.png',
        name: 'SancorSalud',
        plan: '1000 B CC',
        price: '$34.016',
        discount: null,
        reintegros: false,
        internacion: 'Hab. compartida',
        medico: 'Con límite y copago',
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '40%',
        odontologia: true,
        ortodoncia: 'De 5 a 25 años',
        implantes: false,
        oftalmologia: true,
        optica: '1 par x año',
        mental: '30 sesiones',
        kinesiologia: '25 sesiones',
        maternidad: true,
        cirugia: false,
        cobertura: 'AMBA'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-premedic.png',
        name: 'PREMEDIC',
        plan: '500',
        price: '$52.257,12',
        discount: null,
        reintegros: true,
        internacion: 'Hab. individual',
        medico: true,
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '50%',
        odontologia: true,
        ortodoncia: true,
        implantes: true,
        oftalmologia: true,
        optica: 'Reintegro anual',
        mental: '30 sesiones',
        kinesiologia: true,
        maternidad: true,
        cirugia: '1 zona cada 2 años',
        cobertura: 'Nacional'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-doctored.png',
        name: 'DOCTORED',
        plan: 'DOCTORED 1000',
        price: '$25.257,42',
        discount: '$35.000,42',
        reintegros: false,
        internacion: 'Hab. compartida',
        medico: 'Con límite y copago',
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '40%',
        odontologia: true,
        ortodoncia: 'De 5 a 25 años',
        implantes: false,
        oftalmologia: true,
        optica: '1 par x año',
        mental: '30 sesiones',
        kinesiologia: '25 sesiones',
        maternidad: true,
        cirugia: false,
        cobertura: 'AMBA'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-ps.png',
        name: 'Prev. Salud',
        plan: 'A5',
        price: '$20.000,22',
        discount: null,
        reintegros: true,
        internacion: 'Hab. individual',
        medico: true,
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '50%',
        odontologia: true,
        ortodoncia: true,
        implantes: true,
        oftalmologia: true,
        optica: 'Reintegro anual',
        mental: '30 sesiones',
        kinesiologia: true,
        maternidad: true,
        cirugia: '1 zona cada 2 años',
        cobertura: 'Nacional'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-sarcor.png',
        name: 'SancorSalud',
        plan: '1000 B CC',
        price: '$34.016',
        discount: null,
        reintegros: false,
        internacion: 'Hab. compartida',
        medico: 'Con límite y copago',
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '40%',
        odontologia: true,
        ortodoncia: 'De 5 a 25 años',
        implantes: false,
        oftalmologia: true,
        optica: '1 par x año',
        mental: '30 sesiones',
        kinesiologia: '25 sesiones',
        maternidad: true,
        cirugia: false,
        cobertura: 'AMBA'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-premedic.png',
        name: 'PREMEDIC',
        plan: '500',
        price: '$52.257,12',
        discount: null,
        reintegros: true,
        internacion: 'Hab. individual',
        medico: true,
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '50%',
        odontologia: true,
        ortodoncia: true,
        implantes: true,
        oftalmologia: true,
        optica: 'Reintegro anual',
        mental: '30 sesiones',
        kinesiologia: true,
        maternidad: true,
        cirugia: '1 zona cada 2 años',
        cobertura: 'Nacional'
    }
]