export const results = [
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-doctored.png',
        plan: 'DOCTORED 1000',
        price: '$25.257,42',
        discount: '$35.000,42',
        reintegros: false,
        internacion: 'Hab. compartida',
        medico: 'Con límite y copago',
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '40%',
        odontologia: true,
        ortodoncia: 'De 5 a 25 años',
        implantes: false,
        oftalmologia: true,
        optica: '1 par x año',
        mental: '30 sesiones',
        kinesiologia: '25 sesiones',
        maternidad: true,
        cirugia: false,
        cobertura: 'AMBA'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-ps.png',
        plan: 'A5',
        price: '$20.000,22',
        discount: null,
        reintegros: true,
        internacion: 'Hab. individual',
        medico: true,
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '50%',
        odontologia: true,
        ortodoncia: true,
        implantes: true,
        oftalmologia: true,
        optica: 'Reintegro anual',
        mental: '30 sesiones',
        kinesiologia: true,
        maternidad: true,
        cirugia: '1 zona cada 2 años',
        cobertura: 'Nacional'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-sarcor.png',
        plan: '1000 B CC',
        price: '$34.016',
        discount: null,
        reintegros: false,
        internacion: 'Hab. compartida',
        medico: 'Con límite y copago',
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '40%',
        odontologia: true,
        ortodoncia: 'De 5 a 25 años',
        implantes: false,
        oftalmologia: true,
        optica: '1 par x año',
        mental: '30 sesiones',
        kinesiologia: '25 sesiones',
        maternidad: true,
        cirugia: false,
        cobertura: 'AMBA'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-premedic.png',
        plan: '500',
        price: '$52.257,12',
        discount: null,
        reintegros: true,
        internacion: 'Hab. individual',
        medico: true,
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '50%',
        odontologia: true,
        ortodoncia: true,
        implantes: true,
        oftalmologia: true,
        optica: 'Reintegro anual',
        mental: '30 sesiones',
        kinesiologia: true,
        maternidad: true,
        cirugia: '1 zona cada 2 años',
        cobertura: 'Nacional'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-doctored.png',
        plan: 'DOCTORED 1000',
        price: '$25.257,42',
        discount: '$35.000,42',
        reintegros: false,
        internacion: 'Hab. compartida',
        medico: 'Con límite y copago',
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '40%',
        odontologia: true,
        ortodoncia: 'De 5 a 25 años',
        implantes: false,
        oftalmologia: true,
        optica: '1 par x año',
        mental: '30 sesiones',
        kinesiologia: '25 sesiones',
        maternidad: true,
        cirugia: false,
        cobertura: 'AMBA'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-ps.png',
        plan: 'A5',
        price: '$20.000,22',
        discount: null,
        reintegros: true,
        internacion: 'Hab. individual',
        medico: true,
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '50%',
        odontologia: true,
        ortodoncia: true,
        implantes: true,
        oftalmologia: true,
        optica: 'Reintegro anual',
        mental: '30 sesiones',
        kinesiologia: true,
        maternidad: true,
        cirugia: '1 zona cada 2 años',
        cobertura: 'Nacional'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-sarcor.png',
        plan: '1000 B CC',
        price: '$34.016',
        discount: null,
        reintegros: false,
        internacion: 'Hab. compartida',
        medico: 'Con límite y copago',
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '40%',
        odontologia: true,
        ortodoncia: 'De 5 a 25 años',
        implantes: false,
        oftalmologia: true,
        optica: '1 par x año',
        mental: '30 sesiones',
        kinesiologia: '25 sesiones',
        maternidad: true,
        cirugia: false,
        cobertura: 'AMBA'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-premedic.png',
        plan: '500',
        price: '$52.257,12',
        discount: null,
        reintegros: true,
        internacion: 'Hab. individual',
        medico: true,
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '50%',
        odontologia: true,
        ortodoncia: true,
        implantes: true,
        oftalmologia: true,
        optica: 'Reintegro anual',
        mental: '30 sesiones',
        kinesiologia: true,
        maternidad: true,
        cirugia: '1 zona cada 2 años',
        cobertura: 'Nacional'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-doctored.png',
        plan: 'DOCTORED 1000',
        price: '$25.257,42',
        discount: '$35.000,42',
        reintegros: false,
        internacion: 'Hab. compartida',
        medico: 'Con límite y copago',
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '40%',
        odontologia: true,
        ortodoncia: 'De 5 a 25 años',
        implantes: false,
        oftalmologia: true,
        optica: '1 par x año',
        mental: '30 sesiones',
        kinesiologia: '25 sesiones',
        maternidad: true,
        cirugia: false,
        cobertura: 'AMBA'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-ps.png',
        plan: 'A5',
        price: '$20.000,22',
        discount: null,
        reintegros: true,
        internacion: 'Hab. individual',
        medico: true,
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '50%',
        odontologia: true,
        ortodoncia: true,
        implantes: true,
        oftalmologia: true,
        optica: 'Reintegro anual',
        mental: '30 sesiones',
        kinesiologia: true,
        maternidad: true,
        cirugia: '1 zona cada 2 años',
        cobertura: 'Nacional'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-sarcor.png',
        plan: '1000 B CC',
        price: '$34.016',
        discount: null,
        reintegros: false,
        internacion: 'Hab. compartida',
        medico: 'Con límite y copago',
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '40%',
        odontologia: true,
        ortodoncia: 'De 5 a 25 años',
        implantes: false,
        oftalmologia: true,
        optica: '1 par x año',
        mental: '30 sesiones',
        kinesiologia: '25 sesiones',
        maternidad: true,
        cirugia: false,
        cobertura: 'AMBA'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-premedic.png',
        plan: '500',
        price: '$52.257,12',
        discount: null,
        reintegros: true,
        internacion: 'Hab. individual',
        medico: true,
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '50%',
        odontologia: true,
        ortodoncia: true,
        implantes: true,
        oftalmologia: true,
        optica: 'Reintegro anual',
        mental: '30 sesiones',
        kinesiologia: true,
        maternidad: true,
        cirugia: '1 zona cada 2 años',
        cobertura: 'Nacional'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-doctored.png',
        plan: 'DOCTORED 1000',
        price: '$25.257,42',
        discount: '$35.000,42',
        reintegros: false,
        internacion: 'Hab. compartida',
        medico: 'Con límite y copago',
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '40%',
        odontologia: true,
        ortodoncia: 'De 5 a 25 años',
        implantes: false,
        oftalmologia: true,
        optica: '1 par x año',
        mental: '30 sesiones',
        kinesiologia: '25 sesiones',
        maternidad: true,
        cirugia: false,
        cobertura: 'AMBA'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-ps.png',
        plan: 'A5',
        price: '$20.000,22',
        discount: null,
        reintegros: true,
        internacion: 'Hab. individual',
        medico: true,
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '50%',
        odontologia: true,
        ortodoncia: true,
        implantes: true,
        oftalmologia: true,
        optica: 'Reintegro anual',
        mental: '30 sesiones',
        kinesiologia: true,
        maternidad: true,
        cirugia: '1 zona cada 2 años',
        cobertura: 'Nacional'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-sarcor.png',
        plan: '1000 B CC',
        price: '$34.016',
        discount: null,
        reintegros: false,
        internacion: 'Hab. compartida',
        medico: 'Con límite y copago',
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '40%',
        odontologia: true,
        ortodoncia: 'De 5 a 25 años',
        implantes: false,
        oftalmologia: true,
        optica: '1 par x año',
        mental: '30 sesiones',
        kinesiologia: '25 sesiones',
        maternidad: true,
        cirugia: false,
        cobertura: 'AMBA'
    },
    {
        logo: 'https://blinkimages.s3.amazonaws.com/os/logo-premedic.png',
        plan: '500',
        price: '$52.257,12',
        discount: null,
        reintegros: true,
        internacion: 'Hab. individual',
        medico: true,
        guardia: true,
        consultas: true,
        laboratorio: true,
        diagnostico: true,
        farmacias: '50%',
        odontologia: true,
        ortodoncia: true,
        implantes: true,
        oftalmologia: true,
        optica: 'Reintegro anual',
        mental: '30 sesiones',
        kinesiologia: true,
        maternidad: true,
        cirugia: '1 zona cada 2 años',
        cobertura: 'Nacional'
    }
]